# Generated by Django 4.2.3 on 2023-10-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=500, null=True)),
                ('profilepicture', models.ImageField(blank=True, null=True, upload_to='media')),
                ('experience', models.TextField(max_length=5000, null=True)),
            ],
        ),
    ]
