# Generated by Django 4.2.3 on 2023-10-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaches',
            name='experience',
            field=models.TextField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coaches',
            name='name',
            field=models.CharField(default='Kaiden', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coaches',
            name='phone',
            field=models.CharField(default='4792287621', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coaches',
            name='profilepicture',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
