# Generated by Django 4.2.3 on 2024-01-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_coaches_experience_alter_coaches_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='coaches',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='coaches',
            name='name',
        ),
        migrations.RemoveField(
            model_name='coaches',
            name='profilepicture',
        ),
        migrations.AddField(
            model_name='coaches',
            name='bio',
            field=models.TextField(default='kaiden'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coaches',
            name='first_name',
            field=models.CharField(default='kaiden', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coaches',
            name='last_name',
            field=models.CharField(default='kaiden', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coaches',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='coaches',
            name='zip_code',
            field=models.CharField(default=30117, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coaches',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='coaches',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
