# Generated by Django 5.0.3 on 2024-04-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_coaches_price_hour_alter_coaches_price_thirty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaches',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
