# Generated by Django 4.2.3 on 2024-01-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_athlete_remove_coaches_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaches',
            name='my_field',
            field=models.CharField(choices=[('1', 'Coed'), ('2', 'All-Girl')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='coaches',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
