# Generated by Django 5.0.4 on 2024-04-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_coaches_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Link to Instagram Reel'),
        ),
    ]
