# Generated by Django 4.2.3 on 2024-01-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_coaches_my_field_coaches_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coaches',
            old_name='my_field',
            new_name='coed_allgirl',
        ),
    ]
