# Generated by Django 4.2.3 on 2024-01-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_coaches_coed_allgirl'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaches',
            name='coach_tumbling',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='No', max_length=10),
        ),
    ]
