# Generated by Django 4.2.3 on 2024-02-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_coaches_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coaches',
            name='video',
        ),
    ]
