# Generated by Django 4.2.3 on 2024-02-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_coaches_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
